### ISSUE TITLE
Use BattleLevels in my plugin

### ISSUE THREAD

**Issue by magoreo** [RobiRami/BattleLevels#2]
Hello there! I am trying to create a plugin and I need information about the player's Battle Level, in order to use it on a variable. I am kinda new to the plugin thing, can you help me out on how to do that? Thanks in advance

**Comment by RobiRami** [comment]
Please check the wiki and let me know if you have any issues: https://github.com/RobiRami/BattleLevels/wiki

**Comment by magoreo** [comment]
In order to use all those methods, I just need to add Battlelevels.jar as a library? or I need to do more? Because I changed the build bath but still cant use the methods,

**Comment by RobiRami** [comment]
Yes, that should work fine.
Here's a jar specific for using it as an API: http://www.robindebaets.be/BattleLevels.jar

**Comment by magoreo** [comment]
This is my code:

import me.robin.battlelevels.api.BattleLevelsAPI;

...

 public boolean testRequirement(Player player, Map<String, Object> data) {
    	
    	Plugin pl = Bukkit.getPluginManager().getPlugin("BattleLevels");
    	if(pl != null) {
    		
    		boolean flag = false;
    		
    		int level = (int) data.get("Has_Level");  //this is the level limit that a quest requirement has
    		
    		int playerLevel = 0; //I need to add here the players level
    		
    		if(playerLevel>=level) {
    			flag = true;
    		}
            
            return flag;
    	}
    	return false;
    }

around here: http://prnt.sc/dngodq I was expecting to say something like: use method from the BattleLevelsAPI or something.
maybe I am rly dump and I dont understand my mistake. 
Thanks in advance

**Comment by RobiRami** [comment]
BattleLevelsAPI.getLevel(uuid)

Everything's in the wiki...

**Comment by magoreo** [comment]
Ahhhh damm me, I am kinda still a newbie...
Thanks a lot RobiRami for the assistance!!!
